{{- range $name, $svc := .Values.api.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openrmf.fullname" $ }}-api-{{ $name }}
  namespace: {{ include "openrmf.namespace" $ }}
  labels:
    {{- include "openrmf.labels" $ | nindent 4 }}
    app.kubernetes.io/component: api-{{ $name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openrmf.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: api-{{ $name }}
{{- end }}
