apiVersion: v1
kind: Service
metadata:
  name: {{ include "openrmf.fullname" . }}-nats
  namespace: {{ include "openrmf.namespace" . }}
  labels:
    {{- include "openrmf.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.nats.port }}
      targetPort: client
      protocol: TCP
      name: client
    - port: {{ .Values.nats.monitorPort }}
      targetPort: monitor
      protocol: TCP
      name: monitor
  selector:
    {{- include "openrmf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats
