apiVersion: v1
kind: Service
metadata:
  name: {{ include "openrmf.fullname" . }}-web
  namespace: {{ include "openrmf.namespace" . }}
  labels:
    {{- include "openrmf.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "openrmf.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
