apiVersion: v2
name: openrmf
description: >-
  OpenRMF OSS - DoD Risk Management Framework compliance tool for managing
  STIGs, Nessus scans, and NIST RMF compliance. Hardened for STIG'd RKE2
  with Gateway API HTTPS and restricted Pod Security Standard.
type: application
version: 1.14.0
appVersion: "1.14.00"

keywords:
  - openrmf
  - rmf
  - stig
  - nist
  - compliance
  - dod

sources:
  - https://github.com/Cingulara/openrmf-docs

annotations:
  licenses: MIT

maintainers:
  - name: darkhonor
    url: https://www.vmhomelab.org

dependencies:
  - name: keycloakx
    repository: https://codecentric.github.io/helm-charts
    version: "2.4.4"
    condition: keycloak.internal.enabled
  - name: community-operator
    repository: https://mongodb.github.io/helm-charts
    version: "0.11.0"
    condition: mongodb.operator.enabled
