{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "open-webui.name" . }}
  namespace: {{ include "open-webui.namespace" . }}
  labels:
    {{- include "open-webui.labels" . | nindent 4 }}
    {{- with .Values.gateway.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.gateway.annotations }}
  annotations:
    {{- tpl (toYaml .Values.gateway.annotations | nindent 4) . }}
  {{- end }}
spec:
  {{- with .Values.gateway.class }}
  gatewayClassName: {{  }}
  {{- end }}
  listeners:
    - name: https
      protocol: {{ .Values.gateway.listener.protocol | default "HTTPS" }}
      port: {{ .Values.gateway.listener.port | default 443 }}
      hostname: {{ .Values.gateway.host }}
      {{- if .Values.gateway.tls.enabled }}
      tls:
        mode: {{ .Values.gateway.tls.mode | default Terminate | quote }}
        {{- if eq .Values.gateway.tls.mode "Terminate" }}
        certificateRefs:
          - name: {{ include "open-webui.name" . }}-tls
            namespace: {{ include "open-webui.namespace" . }}
        {{- end }}
      {{- end }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
