{{- if .Values.vault-secrets.enabled }}
{{- if .Values.enableOpenaiApi }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-openai-api-key
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.openai-api.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.openai-api.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault-secrets.openai-api.secretName }}
{{- end }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-admin-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.webui-admin.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.webui-admin.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault-secrets.webui-admin.secretName }}
{{- if .Values.sso.google.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-google-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.google.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.google.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault-secrets.google.secretName }}
{{- end }}
{{- if .Values.sso.microsoft.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-microsoft-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.microsoft.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.microsoft.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault-secrets.microsoft.secretName }}
{{- end }}
{{- if .Values.sso.github.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-github-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.github.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.github.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault-secrets.github.secretName }}
{{- end }}
{{- if .Values.sso.oidc.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-oidc-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.oidc.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.oidc.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vault-secrets.oidc.secretName }}
{{- end }}
{{- if eq "s3" .Values.persistence.provider }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-s3-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.s3.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.s3.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.persistence.s3.accessKeyExistingSecret }}
{{- end }}
{{- if eq "gcs" .Values.persistence.provider }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-gcs-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.gcs.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.gcs.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.persistence.gcs.appCredentialsJsonExistingSecret }}
{{- end }}
{{- if eq "azure" .Values.persistence.provider }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-azure-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vault-secrets.authRef }}
  mount: {{ .Values.vault-secrets.azure.mountPoint }}
  type: kv-v2
  path: {{ .Values.vault-secrets.azure.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.persistence.azure.keyExistingSecret }}
{{- end }}
{{- end }}