{{- if .Values.vaultSecrets.enabled }}
{{- if .Values.enableOpenaiApi }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-openai-api-key
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.openaiApi.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.openaiApi.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vaultSecrets.openaiApi.secretName }}
{{- end }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-admin-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.webuiAdmin.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.webuiAdmin.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vaultSecrets.webuiAdmin.secretName }}
{{- if and .Values.sso.enabled .Values.sso.google.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-google-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.google.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.google.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vaultSecrets.google.secretName }}
{{- end }}
{{- if and .Values.sso.enabled .Values.sso.microsoft.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-microsoft-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.microsoft.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.microsoft.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vaultSecrets.microsoft.secretName }}
{{- end }}
{{- if and .Values.sso.enabled .Values.sso.github.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-github-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.github.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.github.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vaultSecrets.github.secretName }}
{{- end }}
{{- if and .Values.sso.enabled .Values.sso.oidc.enabled }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-oidc-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.oidc.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.oidc.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.vaultSecrets.oidc.secretName }}
{{- end }}
{{- if .Values.persistence.enabled }}
{{- if eq "s3" .Values.persistence.provider }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-s3-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.s3.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.s3.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.persistence.s3.accessKeyExistingSecret }}
{{- end }}
{{- if eq "gcs" .Values.persistence.provider }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-gcs-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.gcs.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.gcs.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.persistence.gcs.appCredentialsJsonExistingSecret }}
{{- end }}
{{- if eq "azure" .Values.persistence.provider }}
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: webui-azure-secret
  namespace: {{ include "open-webui.namespace" . }}
spec:
  vaultAuthRef: {{ .Values.vaultSecrets.authRef }}
  mount: {{ .Values.vaultSecrets.azure.mountPoint }}
  type: kv-v2
  path: {{ .Values.vaultSecrets.azure.path }}
  refreshAfter: 60s
  destination:
    create: true
    name: {{ .Values.persistence.azure.keyExistingSecret }}
{{- end }}
{{- end }}
{{- end }}