apiVersion: v2
name: searxng
description: SearXNG is a free internet metasearch engine
home: https://docs.searxng.org
type: application
version: 2026.3.8
appVersion: "2026.3.8-a563127a2"
keywords:
  - searxng
  - search
  - metasearch
  - kubernetes
  - privacy
sources:
  - https://github.com/darkhonor/helm-charts
  - https://github.com/searxng/searxng
annotations:
  licenses: Apache-2.0
maintainers:
  - name: darkhonor
    url: https://www.vmhomelab.org
dependencies:
  - name: valkey
    repository: https://valkey.io/valkey-helm/
    version: 0.9.3
    condition: valkey.enabled
