{{- if .Values.config.limiter.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "searxng.fullname" . }}-limiter
  namespace: {{ include "searxng.namespace" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
data:
  limiter.toml: |
    {{- .Values.config.limiter.data | nindent 4 }}
{{- end }}
