apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "searxng.fullname" . }}
  namespace: {{ include "searxng.namespace" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "searxng.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "searxng.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "searxng.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.dns.configure }}
      dnsPolicy: {{ .Values.dns.policy | quote }}
      dnsConfig:
        {{- with .Values.dns.config.nameservers }}
        nameservers:
          - 10.43.0.10
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.dns.config.searches }}
        searches:
          {{- toYaml . | nindent 10 }}
          - svc.cluster.local
          - cluster.local
        {{- end }}
        {{- with .Values.dns.config.options }}
        options:
          {{- toYaml . | nindent 10 }}
          - name: edns0
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SEARXNG_BASE_URL
              value: https://{{ .Values.httproute.hostname | quote }}
            - name: SEARXNG_HOSTNAME
              value: {{ .Values.httproute.hostname | quote }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.config.settings.enabled }}
            - mountPath: /etc/searxng/settings.yml
              name: searxng-settings
              subPath: settings.yml
              readOnly: true
          {{- end }}
          {{- if .Values.config.limiter.enabled }}
            - mountPath: /etc/searxng/limiter.toml
              name: searxng-limiter
              subPath: limiter.toml
              readOnly: true
          {{- end }}
          {{- if .Values.config.uwsgi.enabled }}
            - mountPath: /etc/searxng/uwsgi.ini
              name: searxng-uwsgi
              subPath: uwsgi.ini
              readOnly: true
          {{- end }}
            - mountPath: /tmp
              name: searxng-tmp
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- if .Values.config.settings.enabled }}
        - name: searxng-settings
          configMap:
            name: {{ include "searxng.fullname" . }}-settings
      {{- end }}
      {{- if .Values.config.limiter.enabled }}
        - name: searxng-limiter
          configMap:
            name: {{ include "searxng.fullname" . }}-limiter
      {{- end }}
      {{- if .Values.config.uwsgi.enabled }}
        - name: searxng-uwsgi
          configMap:
            name: searxng-uwsgi
      {{- end }}
        - name: searxng-tmp
          emptyDir: {}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
