{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "searxng.name" . }}
  namespace: {{ include "searxng.namespace" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
    {{- with .Values.httproute.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.httproute.annotations }}
  annotations:
    {{- tpl (toYaml .Values.httproute.annotations | nindent 4) . }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ include "searxng.fullname" . }}-gateway
      namespace: {{ include "searxng.namespace" . }}
  hostnames:
    - {{ .Values.httproute.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "searxng.fullname" . }}
          namespace: {{ include "searxng.namespace" . }}
          port: {{ .Values.service.port }}
{{- end }}
