{{- if .Values.secrets.searxngSecret.create }}
{{- $secretName := include "searxng.secretName" . }}
{{- $secretKey := .Values.secrets.searxngSecret.key }}
{{- $existingSecret := lookup "v1" "Secret" (include "searxng.namespace" .) $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ include "searxng.namespace" . }}
  labels:
    {{- include "searxng.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $existingSecret (not .Values.secrets.searxngSecret.value) }}
  {{ $secretKey }}: {{ index $existingSecret.data $secretKey }}
  {{- else }}
  {{ $secretKey }}: {{ default (randAlphaNum 64) .Values.secrets.searxngSecret.value | b64enc | quote }}
  {{- end }}
{{- end }}
